name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate GitHub contribution metrics
        uses: lowlighter/metrics@latest
        with:
          user: Chebil-Ilef
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: activity, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_lines: yes
          config_timezone: Europe/Berlin
          config_order: isocalendar, languages, lines, base.activity, base.metadata
          config_padding: 10,20
          optimize: yes
